pool:
  vmImage: ubuntu-latest

steps:
- task: ArchiveFiles@2
  displayName: 'Create package'
  inputs:
    rootFolderOrFile: '$(Build.Repository.LocalPath)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/PasswordGenerator-$(Build.BuildNumber).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: 'Drop artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: store-publish@0
  displayName: 'Deploy package'
  inputs:
    serviceEndpoint: 'Microsoft Partner Center Connection'
    appId: '0RDCKDGH3MWT'
    packagePath: '$(Build.ArtifactStagingDirectory)/PasswordGenerator-$(Build.BuildNumber).zip'
    force: true
    skipPolling: true